name: Histórico de alterações

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'

  pull_request:
    branches:
      - main
      - develop

jobs:
  registrar:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar informações do commit
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Autor: ${{ github.actor }}"
          echo "Mensagem: ${{ github.event.head_commit.message }}"